
on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  triage-issue:
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.issue.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest

    # コメントがgeminiで始まる場合のみ実行
    if: startsWith(github.event.comment.body, 'gemini')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run Gemini CLI from the main branch
        uses: google-gemini/gemini-cli-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            ${{ github.event.comment.body }}

            ### 前提
            - 確認は不要です
            - 常に日本語で返答してください
            - エラーが発生した場合は、常にエラー内容を出力してください

            ### Issue情報
            - Repository: ${{ github.repository }}
            - Issue 番号: ${{ github.event.issue.number }}
            - Issue タイトル: ${{ github.event.issue.title }}
            - Issue 本文: ${{ github.event.issue.body }}

            ### PR作成手順
            1. git checkout -b issue-${{ github.event.issue.number }}
            2. git add -A
            3. git commit -m "{{修正内容}}"
            4. git push origin issue-${{ github.event.issue.number }}
            5. gh pr create --title "{{PRタイトル}}" --body "{{PR内容}}"

      - name: Commit Changes
        id: commit
        run: |
          git branch
          git status
