
on:
  issue_comment:
    types: [created]

jobs:
  triage-issue:
    timeout-minutes: 10
    permissions:
      issues: write
      contents: read
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.issue.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest

    # コメントがgeminiで始まる場合のみ実行
    if: startsWith(github.event.comment.body, 'gemini')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run Gemini CLI from the main branch
        uses: google-gemini/gemini-cli-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY: ${{ github.repository }}
        with:
          version: latest
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          settings_json: |
            {
              "coreTools": [
                "run_shell_command(git status)",
                "run_shell_command(git add)",
                "run_shell_command(git commit)",
                "run_shell_command(git push)",
                "run_shell_command(git pull)",
                "run_shell_command(git checkout)",
                "run_shell_command(git switch)",
                "run_shell_command(git branch)",
                "run_shell_command(gh issue list)",
                "run_shell_command(gh issue view)",
                "run_shell_command(gh issue edit)",
                "run_shell_command(gh repo view)",
                "run_shell_command(gh pr list)",
                "run_shell_command(gh pr view)",
                "run_shell_command(gh pr edit)",
                "run_shell_command(gh pr diff)"
              ]
            }
          prompt: |
            ${{ github.event.comment.body }}

            ### Premise
            - No confirmation required.
            - Always respond in Japanese.
            - Use the `gh` command to work with GitHub.

            ### Issue Information
            - Repository: $REPOSITORY
            - Issue Number: $ISSUE_NUMBER
            - Issue Title: $ISSUE_TITLE
            - Issue Body: $ISSUE_BODY
